apiVersion: kro.run/v1alpha1
kind: WordpressServer
metadata:
  name: wordpress-dev
  namespace: development
spec:
  name: wordpress-dev
  namespace: development
  ingress:
    enabled: true
    host: wp-development
  db_password: "dev-password"
  replicas: 1
  storage:
    enabled: true
    storageClass: "local-path"
    wordpress:
      size: "15Gi"
    mariadb:
      size: "25Gi"
