apiVersion: kro.run/v1alpha1
kind: WordpressServer
metadata:
  name: wordpress-prod
  namespace: production
spec:
  name: wordpress-prod
  namespace: production
  ingress:
    enabled: true
    host: wp-production
  db_password: "prod-password"
  replicas: 1
  storage:
    enabled: true
    storageClass: "local-path"
    wordpress:
      size: "15Gi"
    mariadb:
      size: "25Gi"
